import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Dataprovider from "src/context/Dataprovider";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "vflyorions-test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Dataprovider >
          <div  className='bg-slate-100'>
          <Navbar />
          {children}
          <Footer/>
          </div>
        </Dataprovider>
      </body>
    </html>
  );
}
